config/routes.rb
Chleb::Application.routes.draw do

get "gists/search"
  resources :gists do
    resources :comments
  end
  root 'gists#index'

 match '/auth/:provider/callback', :to => 'sessions#create',  via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
	belongs_to :user
	validates :provider, :uid, :presence => true

	def self.find_or_create(auth_hash)
  unless auth = find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    user = User.create :name => auth_hash["extra"]["login"], :email => auth_hash["info"]["email"]
    auth = create :user => user, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
  end
 
  auth
end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :gist
end

app/models/gist.rb
class Gist < ActiveRecord::Base
	has_many :comments
def self.search(search)
     if search
       find(:all, :conditions => ['lang LIKE ?', "%#{search}%"])
     else
       limit(0)
     end
   end
end

app/models/user.rb
class User < ActiveRecord::Base
 def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth[:provider]
      user.uid = auth[:uid]
      user.name = auth[:info][:name]
      user.oauth_token = auth[:credentials][:token]
      #user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @gist = Gist.find(params[:gist_id])
    @comment = @gist.comments.create(comment_params)
    redirect_to gist_path(@gist)
  end
 
def destroy
    @gist = Gist.find(params[:gist_id])
    @comment = @gist.comments.find(params[:id])
    @comment.destroy
    redirect_to gist_path(@gist)
  end


  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  
  # ...
  
  def show
    @community = Community.find(params[:id])
    @users = @community.users
    @ressources = Ressource.paginate(:page => params[:page], :per_page => 5)
  end
 
  # ...  
 
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]

  # GET /gists
  # GET /gists.json
   def index
    get_and_show_gists
  end

  def get_and_show_gists
    @gists = Gist.paginate(page: params[:page], per_page: 12).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

def search
     @gists = Gist.search(params[:lang])
   end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Wrzutka została dodana!' }
        format.json { render action: 'show', status: :created, location: @gist }
      else
        format.html { render action: 'new' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Wrzutka została zaktualizowana!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:snippet, :lang, :description, :autor)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  def failure

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def facebook_like
            content_tag :iframe, nil, :src => "http://www.facebook.com/plugins/like.php?href=#{CGI::escape(request.url)}&layout=standard&show_faces=true&width=450&action=like&font=arial&colorscheme=light&height=80", :scrolling => 'no', :frameborder => '0', :allowtransparency => true, :id => :facebook_like
          end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>
<%
allowed = Pygments.lexers.flatten.select.with_index{|a,i| (i+1) % 2 == 0}
allowed = allowed.map{|a| a[:aliases][0]}
allowed = allowed.sort
%>
  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>

      <ul>
      <% @gist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="field">

    <%= f.label :Wrzutka %>
    <%= f.text_area :snippet, :size => "80x10" %>
  </div>
  <div class="field" id="jj">
    <%= f.label :Język %>
    <%= f.select :lang, allowed %>
  </div>
  <div class="field">
    <%= f.label :Opis %>
    <%= f.text_field :description %>
  </div>


  <div class="actions">
    <%= f.submit :Gotowe, style:"width: 100px;" %>
  </div>

<% end %>

app/views/gists/_gist.html.erb
<div class = "col-lg-4">
                  <table class="table table-striped table-condensed table-hover table-responsive">
                      <thead>
    <tr>
      <th>Wrzutka</th>
      <th>Język</th>
      <th>Opis</th>
      <th>Autor</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
                    <tr class="success">
                <td><span><%= raw Pygments.highlight(gist.snippet.length > 30 ? gist.snippet[0,30] + "..." : gist.snippet, lexer: gist.lang) %></span></td>
                
               <td> <span><%= gist.lang %></span></td>
                
                <td><span><%= gist.description %></span></td>

                <!-- <td><span style="width: 20px; overflow: ellipsis;"><%= gist.autor %></span></td> -->
                <td><span style="display: block; white-space: nowrap; width: 60px; overflow: hidden; text-overflow: ellipsis;"><%= gist.autor %></span></td>

               <td><div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    Opcje <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <% if current_user %>
    <li><a href="#"><%= link_to 'Pokaż', gist %></a></li>
    <li><a href="#"><%= link_to 'Edytuj', edit_gist_path(gist) %></a></a></li>
    <li><a href="#"><%= link_to 'Usuń', gist, method: :delete, data: { confirm: 'Jesteś pewien, że chcesz usunąć wrzutkę?' } %></a></li>
    <% else %>
    <li><a href="#"><%= link_to 'Pokaż', gist %></a></li>
    <% end %>
  </ul>
</div></td>
</tr>
</table>
</div>

app/views/gists/edit.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <a class="brand">Marek Bednarczyk - "Lepsza wersja My gists"</a>
  </div>
</div>
<div class="jumbotron">
            <div class="container">

<h1>Edytowanie wrzutki</h1>
<br>

<%= render 'form' %>
<div class="btn-group btn-group-xl">
<button type="button" class="btn btn-default">
<%= link_to 'Pokaż', @gist %></button>
<button type="button" class="btn btn-default"><%= link_to 'Powrót', gists_path %></button>
</div>
</div>
</div>

app/views/gists/index.html.erb
<%- model_class = Gist -%>

<!-- <div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <a class="brand" href="/gists">Marek Bednarczyk - Lepsza wersja My gists</a>
    <ul class="nav">
      <li class="active"><a href="/gists">Home</a></li>
      <li class="divider-vertical"></li>
      <li><a href="/gists/new">Nowa wrzutka</a></li>
      <li class="divider-vertical"></li>
      <li class="dropdown">
                <% if current_user %>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Signed in as <strong><%= current_user.name %><b class="caret"></b></strong></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
                    </ul>
                <% else %>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign in<b class="caret"></b></strong></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Sign in with GitHub", "/auth/github", id: "sign_in" %></li>
                    </ul>
                <% end %>
            </li>
    </ul>
    <ul class="nav pull-right hidden-xs">
          <form class="navbar-form navbar-left pull-right" role="search" action="/gists/search">
          <div class="form-group">
 
        <%= select_tag(:lang, options_for_select(Pygments.lexers.keys.sort.map! {|l| l.downcase.strip}, params[:lang]))%>
          </div>
          <button type="submit" class="btn btn-default">Search</button>
        </form>
        
        </ul>
      </nav>
  </div>
</div> -->




<!--     <nav role="navigation" class="navbar navbar-inverse">

        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">Marek Bednarczyk - Lepsza wersja My gists</a>
        </div>

        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/gists">Home</a></li>
                <li><a href="/gists/new">Nowa wrzutka</a></li>
            </ul>
                      <form class="navbar-form navbar-left pull-right" role="search" action="/gists/search">
          <div class="form-group">
 
        <%= select_tag(:lang, options_for_select(Pygments.lexers.keys.sort.map! {|l| l.downcase.strip}, params[:lang]))%>
          </div>
          <button type="submit" class="btn btn-default">Search</button>
        </form>
            <ul class="nav navbar-nav navbar-right">
            </ul>
        </div>
    </nav>  -->




<div id="infinite-scrolling" style="visibility: hidden;">
  <%= will_paginate %>
</div>

<div id="my-gists">
    <div class="jumbotron">
            <div class="container">
              <h1>Lista naszych wrzutek</h1>
          <div class = "row">
      <%= render @gists %>

</div>
<div class="icon"></div>
</div>
            </div>

          </div>













      

        

 <!-- .container -->

 
     
     <div class="navbar navbar-default navbar-fixed-bottom">
        <div class="navbar-inner">
          <p class="navbar-text pull-center"><%= facebook_like %></p>
        </div>
     </div>

app/views/gists/index.js.erb
var delimiter =
$('<div class="page-delimiter"  data-page="<%= params[:page] %>"></div>');
$('.row').append(delimiter);
$('.row').append('<%= j render @gists %>');
$('.pagination').replaceWith('<%= j will_paginate @gists %>');
preparePagination(delimiter);

<% unless @gists.next_page %>
$('#infinite-scrolling .pagination').remove();
<% end %>

app/views/gists/new.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <a class="brand">Marek Bednarczyk - "Lepsza wersja My gists"</a>
  </div>
</div>
<div class="jumbotron">
            <div class="container">
  	<h1>Nowa wrzutka</h1>

<%= render 'form' %>


<%= link_to 'Powrót', gists_path %>
</div>
</div>

app/views/gists/search.html.erb
<% if(@gists.length > 0) %>
<%- model_class = Gist -%>
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <a class="brand" href="/gists">Marek Bednarczyk - Lepsza wersja My gists</a>
    <ul class="nav">
    	<li class="active"><a href="/gists">Home</a></li>
      <li class="divider-vertical"></li>
      <li><a href="/gists/new">Nowa wrzutka</a></li>
      <li class="divider-vertical"></li>
    </ul>
    <ul class="nav pull-right">
          <form class="navbar-form navbar-left pull-right" role="search" action="/gists/search">
          <div class="form-group">
 
        <%= select_tag(:lang, options_for_select(Pygments.lexers.keys.sort.map! {|l| l.downcase.strip}, params[:lang]))%>
          </div>
          <button type="submit" class="btn btn-default">Search</button>
        </form>
        
        </ul>
      </nav>
  </div>
</div>



<div id="my-gists">
    <div class="jumbotron">
            <div class="container">
              <h1>Lista wyszukancyh wrzutek</h1>
          <div class = "row">
      <%= render @gists %>
</div>
</div>
            </div>
          </div>
</div>
        </div>


 <!-- .container -->

 
     
     <div class="navbar navbar-default navbar-fixed-bottom">
        <div class="navbar-inner">
          <p class="navbar-text pull-center"><%= facebook_like %></p>
        </div>
     </div>

<% else if(@gists.length == 0) %>
    <div class="alert alert-info">
      <strong>No gists found.</strong>
    </div>
<% end end %>

app/views/gists/show.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <a class="brand">Marek Bednarczyk - "Lepsza wersja My gists"</a>
  </div>
</div>

<div class="jumbotron">
            <div class="container">
	<div class = "row">
<div class = "col-lg-4">
<p id="notice"><%= notice %></p>

<p>
  <strong>Język</strong>
  <%= @gist.lang %>
</p>
<table class="table table-striped table-condensed table-hover table-responsive">
<thead><tr>
<strong>Wrzutka:</strong>
</tr>
</thead>
<tr><td>
<%= raw Pygments.highlight(@gist.snippet, lexer: @gist.lang) %></tr></td>
</table>
<p>
  <strong>Opis:</strong>
  <%= @gist.description %>
</p>
<p>
   <strong>Autor:</strong>
   <%= @gist.autor %>
 </p>

<h2>Comments</h2>
<% @gist.comments.each do |comment| %>
  <p>
    <%= comment.commenter %>: <%= comment.body %> <%= link_to 'Destroy Comment', [comment.gist, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  </p>
  
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@gist, @gist.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>












<div class="btn-group btn-group-xl">

<button type="button" class="btn btn-default"><%= link_to 'Edytuj', edit_gist_path(@gist) %> </button>
<button type="button" class="btn btn-default"><%= link_to 'Powrót', gists_path %> </button>

<button type="button" class="btn btn-default"><%= link_to 'Powrót', gists_path %> </button>

</div>


</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gisty</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
      <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
      <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
	<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <a class="brand" href="/gists">GITpower Team - Exam</a>
    <ul class="nav">
      <li class="active"><a href="/gists">Home</a></li>
      <li class="divider-vertical"></li>
      <li><a href="/gists/new">Nowa wrzutka</a></li>
      <li class="divider-vertical"></li>
      <li class="dropdown">
                <% if current_user %>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cześć, <strong><%= current_user.name %><b class="caret"></b></strong></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Wyloguj", signout_path, id: "sign_out" %></li>
                    </ul>
                <% else %>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Zaloguj<b class="caret"></b></strong></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Zaloguj via GitHub", "/auth/github", id: "sign_in" %></li>
                        <li><%= link_to "Zaloguj via Facebook", "/auth/facebook", id: "sign_in" %></li>
                    </ul>
                <% end %>
            </li>
    </ul>
    <ul class="nav pull-right hidden-xs">
          <form class="navbar-form navbar-left pull-right" role="search" action="/gists/search">
          <div class="form-group">
 
        <%= select_tag(:lang, options_for_select(Pygments.lexers.keys.sort.map! {|l| l.downcase.strip}, params[:lang]))%>
          </div>
          <button type="submit" class="btn btn-default">Szukaj</button>
        </form>
        
        </ul>
      </nav>
  </div>
</div>

<%= yield %>

</body>
</html>